List<String> bankList() {
  var bankNames = [
    'Accion Microfinance Bank',
    'Access Bank',
    'Citibank',
    'Coronation Merchant Bank',
    'Covenant Microfinance Bank Ltd',
    'Diamond Bank',
    'Dynamic Standard Bank',
    'Ecobank Nigeria',
    'Empire Trust Microfinance Bank',
    'Fidelity Bank Nigeria',
    'Fina Trust Microfinance Bank',
    'Finca Microfinance Bank Limited',
    'First Bank of Nigeria',
    'FBNQuest Merchant Bank',
    'First City Monument Bank',
    'FSDH Merchant Bank',
    'Guaranty Trust Bank',
    'Heritage Bank Plc',
    'Infinity Microfinance Bank',
    'Jaiz Bank',
    'Keystone Bank Limited',
    'Kuda Bank',
    'Mint Finex MFB',
    'Mkobo MFB',
    'Moniepoint Microfinance Bank',
    'Mutual Trust Microfinance Bank',
    'Nova Merchant Bank',
    'Opay',
    'Palmpay',
    'Peace Microfinance Bank',
    'Pearl Microfinance Bank Limited',
    'Providus Bank Plc',
    'Polaris Bank',
    'Rand Merchant Bank',
    'Rephidim Microfinance Bank',
    'Rubies Bank',
    'Shepherd Trust Microfinance Bank',
    'Sparkle Bank',
    'Stanbic IBTC Bank Nigeria Limited',
    'Standard Chartered Bank',
    'Sterling Bank',
    'Suntrust Bank Nigeria Limited',
    'Union Bank of Nigeria',
    'United Bank for Africa',
    'Unity Bank Plc',
    'VFD Microfinance Bank',
    'Wema Bank',
    'Zenith Bank',
  ];

  return bankNames;
}
